### ISSUE TITLE
Wings-Blur Aurorae Theme not functioning correctly with Wayland

### ISSUE THREAD

**Issue by dai5m5iq** [L4ki/Wings-Plasma-Themes#1]
When using Wings-Blur-Light or Wings-Blur-Dark on Wayland the titlebar loses buttons when multiple window are maximized and then restored and maximized again. 
This does not happen with X11. 

Steps to reproduce:

1. Log into Wayland session
2. Open Browser, System settings, Konsole at the same time
3. Leave one window maximized and restore another window, then maximize it again
4. Result: Buttons for Close, Minimize, Restore disappear, window title is misplaced. 

![image](https://user-images.githubusercontent.com/111610689/228414430-7afea88a-47dc-4b8d-a8a0-0f194a05aec6.png)

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.8-1-MANJARO (64-bit)
Graphics Platform: Wayland

**Comment by L4ki** [comment]
Hi dai5m5iq,

Thanks for the info. However, I tried all the variants and everything is fine.

See Screenshots:

1. https://postimg.cc/mzJJqhw4

2. https://postimg.cc/cK5bg6P3

I really don't know why it's like that with you.

Greeting,

**Comment by dai5m5iq** [comment]
Hi L4ki,
Thanks for your fast response. 
I opened the issue after a second user mentioned it also using Wayland. 
Please see the discussion on the Manjaro forum: https://forum.manjaro.org/t/how-to-make-titlebars-blurry-in-plasma/137114/10?u=raguse

I just tried again and I can reproduce it. You may have to restore and maximize the window a few time until it happens. 
I hope not it's specific to Manjaro using KDE. (I used Breeze just now to test.)

Also the below happens: Icons appear in the middle of the titlebar. Looks like it has a scaling issue. 

![image](https://user-images.githubusercontent.com/111610689/228453566-34ded49f-23b0-4274-9ff5-585740b01ba0.png)

One thing to note: I only use the Aurorae theme, not the full Wings Plasma theme.

**Comment by L4ki** [comment]
Hi dai5m5iq,

I'm trying for an hour in all variants. I set the Global Theme "Breeze" with Windows Decorations "Wings-Blur-Light-Aurorae" and "Wings-Blur-Dark-Aurorae". Everything is OK.

I wish that happened to me too, I'd know what to do and try to fix the mistake. This is how I don't know what to do.

Screenshot, Plasma Theme "Breeze" and Aurorae Theme "Wings-Blur-Light-Aurorae": https://postimg.cc/G8YznyZc

Does this happen to you with other "Blur Windows Decorations"?

**Comment by dai5m5iq** [comment]
Hi L4ki, 
Thanks for your investigation. 
This issue seems to be caused by another root cause. I tried with other aurorae themes (not blur) and it also happens. 
I am going to close this issue and will investigate further by trying in a virtual machine and KDE Neon and other distros.
Interestingly there is no issue with the stock Breeze aurorae theme. 

Many thanks again.
