### ISSUE TITLE
Glitched angle when trying to resize the window

### ISSUE THREAD

**Issue by RosGtHub** [L4ki/Wings-Plasma-Themes#2]
This is the issue:
![Screenshot_20230708_031709](https://github.com/L4ki/Wings-Plasma-Themes/assets/89165766/401b7be0-8049-4ab7-84fe-adda63e98f2d)
How can i fix it?

**Comment by L4ki** [comment]
Hi RosGtHub,

I really appreciate you informing me of this error. I already fixed that mistake. The update will be announced tomorrow (before noon). The problem was in widdget translucentbackground.svg. Thank you, best regards,

**Comment by RosGtHub** [comment]
Thank you too.

**Comment by RosGtHub** [comment]
Should it be fixed?
Because i've updated the theme,but didn't work.
![Screenshot_20230709_134616](https://github.com/L4ki/Wings-Plasma-Themes/assets/89165766/383bc063-9aa5-43a6-8388-525f0b8174b6)

**Comment by L4ki** [comment]
Hi RosGtHub,

I checked, everything is fine. 

My Screenshot: ![Screenshot_20230710_082856](https://github.com/L4ki/Wings-Plasma-Themes/assets/45247573/07e450b2-16d2-4360-b89c-b3253100163b)

**Comment by L4ki** [comment]
Try to install manually. 

Download Plasma Theme "Wings-Dark-Plasma": https://www.pling.com/p/1982111 

Extract: Wings-Dark-Plasma.tar.gz

Then manually place the extracted file in: Dolphin > Show Hidden Files > .local > share > plasma > desktoptheme 

Delete the old file "Wings-Dark-Plasma", and put the new one.

Finally: logout or restart

P.S.

It may be easier to first uninstall the Plasma Theme "Wings-Dark-Plasma" in System Settings and then reinstall it.

**Comment by RosGtHub** [comment]
It worked!, thank you. The only way was the manual installation.
