### ISSUE TITLE
Window resizing stutters

### ISSUE THREAD

**Issue by RosGtHub** [L4ki/Wings-Plasma-Themes#4]
Hi, is the lag normal when i resize the windows or maybe is  just a wayland problem? 

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.4.10-arch1-1
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600G with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             14.9 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.4.10-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.5
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.5
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.246)

Monitor: Optix MAG241C 144hz

**Comment by L4ki** [comment]
Hi RosGtHub,

I don't have those problems. Is it the same with other Plasma Themes, or is it the case only with the "Wings" Plasma Theme?

**Comment by RosGtHub** [comment]
With breeze looks fine, i think is the theme. Sometimes when i resize a window happens also this: 
![image](https://github.com/L4ki/Wings-Plasma-Themes/assets/89165766/b9a12eb2-4038-4dee-8ac3-f69bfc5bee60)
Some borders don't fully regenerate, like as you can see at the bottom-right.

Are you on x11 or wayland?

**Comment by L4ki** [comment]
I'm using x11, but I've also tried Wayland. In general Wayland should be better.

**Comment by RosGtHub** [comment]
maybe is the refresh rate of the monitor. Probably the animation is for 60hz and looks laggy on 144hz, i don't know.

**Comment by RosGtHub** [comment]
I tried the dexy theme and it doesn't happen with it or atleast it's alot less visible. The breeze-dark is perfect!
It looks that anything different from breeze causes issues mh....do you have any idea?
