### ISSUE TITLE
Weird shadow behind the window

### ISSUE THREAD

**Issue by RosGtHub** [L4ki/Wings-Plasma-Themes#5]
hi, another bug i guess. Is that shadow behind the window normal?  i don't think, let me know. Because it's very weird and annoying when there's a white/lighter background.
![image](https://github.com/L4ki/Wings-Plasma-Themes/assets/89165766/99bee7b6-1175-4c9f-a1dd-24dfb54673c4)

**Comment by L4ki** [comment]
Hi RosGtHub, 

No, it's not  bug. Now, it all depends on taste. Someone likes that shadow, someone doesn't like it.

Best regards,

**Comment by RosGtHub** [comment]
Alright, thank you!
